# Generated by Django 3.2.23 on 2024-04-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0153_auto_20240214_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaildocument',
            name='activites',
            field=models.ManyToManyField(blank=True, help_text='Sélectionnez une ou plusieurs activités dans la liste.', related_name='document_activites', to='core.Activite', verbose_name='Activités'),
        ),
        migrations.AddField(
            model_name='portaildocument',
            name='groupes',
            field=models.ManyToManyField(blank=True, help_text='Sélectionnez un ou plusieurs groupes dans la liste.', related_name='document_groupes', to='core.Groupe', verbose_name='Groupes'),
        ),
    ]
