# Generated by Django 3.2.23 on 2024-04-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0155_auto_20240422_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarif',
            name='type',
            field=models.CharField(choices=[('FORFAIT', 'Forfait daté')], default='JOURN', max_length=100, verbose_name='Type'),
        ),
    ]
