# Generated by Django 3.2.23 on 2024-05-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0156_alter_tarif_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='modelimp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Modèle d'impression"),
        ),
        migrations.AlterField(
            model_name='adressemail',
            name='moteur',
            field=models.CharField(choices=[('smtp', 'SMTP'), ('mailjet', 'Mailjet'), ('brevo', 'Brevo'), ('console', 'Console')], help_text="Sélectionnez un moteur d'expédition (Smtp ou Mailjet).", max_length=200, verbose_name='Moteur'),
        ),
    ]
