# Generated by Django 3.2.23 on 2024-07-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0157_auto_20240530_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Visible sur le portail'),
        ),
        migrations.AddField(
            model_name='structure',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Visible sur le portail'),
        ),
        migrations.AlterField(
            model_name='activite',
            name='pay_org',
            field=models.BooleanField(default=False, verbose_name='Activation paiement par lien externe'),
        ),
        migrations.AlterField(
            model_name='activite',
            name='portail_inscriptions_affichage',
            field=models.CharField(choices=[('JAMAIS', 'Ne pas autoriser'), ('TOUJOURS', 'Autoriser'), ('PERIODE', 'Autoriser sur la période suivante')], default='TOUJOURS', max_length=100, verbose_name='Inscriptions autorisées'),
        ),
        migrations.AlterField(
            model_name='activite',
            name='portail_inscriptions_imposer_pieces',
            field=models.BooleanField(default=True, verbose_name='Imposer le téléchargement des pièces à fournir'),
        ),
        migrations.AlterField(
            model_name='adressemail',
            name='moteur',
            field=models.CharField(choices=[('smtp', 'SMTP'), ('mailjet', 'Mailjet'), ('brevo', 'Brevo'), ('console', 'Console')], help_text="Sélectionnez un moteur d'expédition (Smtp, Mailjet ou Brevo).", max_length=200, verbose_name='Moteur'),
        ),
    ]
