# Generated by Django 3.2.23 on 2024-07-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0157_auto_20240530_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adressemail',
            name='moteur',
            field=models.CharField(choices=[('smtp', 'SMTP'), ('mailjet', 'Mailjet'), ('brevo', 'Brevo'), ('console', 'Console')], help_text="Sélectionnez un moteur d'expédition (Smtp, Mailjet ou Brevo).", max_length=200, verbose_name='Moteur'),
        ),
    ]
