# Generated by Django 3.2.23 on 2024-07-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0159_auto_20240717_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Visible sur le portail'),
        ),
    ]
