# Generated by Django 3.2.23 on 2024-07-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0160_alter_activite_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Visible sur le portail'),
        ),
    ]
