# Generated by Django 3.2.23 on 2024-07-23 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0158_auto_20240718_1243'),
        ('core', '0161_structure_visible'),
    ]

    operations = [
    ]
