# Generated by Django 3.2.23 on 2024-07-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0163_auto_20240723_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='public',
            field=models.IntegerField(choices=[(0, 'Parent'), (1, 'Chef/taine'), (2, 'Chef/taine de groupe - Directeur/trice'), (3, 'Délégué(e) Local'), (4, 'Ami(e)'), (5, 'Jeunes')], default=5, verbose_name='Public destinataire'),
        ),
        migrations.AlterField(
            model_name='individu',
            name='statut',
            field=models.IntegerField(blank=True, choices=[(0, 'Parent'), (1, 'Chef/taine'), (2, 'Chef/taine de groupe - Directeur/trice'), (3, 'Délégué(e) Local'), (4, 'Ami(e)'), (5, 'Jeunes')], default=0, null=True, verbose_name='Statut'),
        ),
    ]
