# Generated by Django 3.2.23 on 2024-08-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0165_auto_20240725_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglement',
            name='modelimp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Modèle d'impression"),
        ),
    ]
