# Generated by Django 3.2.23 on 2024-08-04 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0166_reglement_modelimp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglement',
            name='modelimp',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='core.modeleimpression', verbose_name="Modèle d'impression"),
            preserve_default=False,
        ),
    ]
