# Generated by Django 3.2.23 on 2024-08-30 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0168_activite_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairequestion',
            name='activite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.activite', verbose_name='Activité'),
        ),
    ]
