# Generated by Django 3.2.23 on 2024-10-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0171_auto_20241001_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='individu',
            name='allergies',
            field=models.ManyToManyField(blank=True, related_name='individu_allergies', to='core.TypeAllergie', verbose_name='Allergies contractées'),
        ),
    ]
