# Generated by Django 3.2.23 on 2024-10-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0173_alter_utilisateur_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='individu',
            name='allergies_detail',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Conduite à tenir'),
        ),
    ]
