# Generated by Django 3.2.23 on 2024-10-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0175_auto_20241001_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individu',
            name='dispmed',
            field=models.ManyToManyField(blank=True, related_name='individu_dispmed', to='core.TypeDispmed', verbose_name='Dispositifs médicaux'),
        ),
    ]
