# Generated by Django 3.2.23 on 2024-10-01 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0178_auto_20241001_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traitement',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Réalisé par'),
        ),
    ]
