# Generated by Django 3.2.23 on 2024-12-05 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0181_alter_utilisateur_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traitement',
            old_name='activite',
            new_name='activites',
        ),
    ]
