# Generated by Django 3.2.23 on 2024-12-05 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0182_rename_activite_traitement_activites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traitement',
            old_name='activites',
            new_name='activite',
        ),
    ]
