# Generated by Django 3.2.23 on 2025-01-07 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0184_auto_20241212_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='portailrenseignement',
            name='activite',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='core.activite', verbose_name='Famille'),
            preserve_default=False,
        ),
    ]
