# Generated by Django 3.2.23 on 2025-01-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0186_alter_portailrenseignement_activite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traitement',
            name='typemaladie',
            field=models.CharField(max_length=50, verbose_name='Pathologie associée'),
        ),
    ]
