# Generated by Django 3.2.23 on 2025-01-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0188_auto_20250121_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individu',
            name='secu',
            field=models.CharField(blank=True, max_length=15, verbose_name='N° de sécurité sociale'),
        ),
    ]
