# Generated by Django 3.2.23 on 2025-03-24 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0192_alter_deduction_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deduction',
            name='label',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.typededuction', verbose_name='Label'),
        ),
    ]
