# Generated by Django 3.2.23 on 2025-05-27 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0194_auto_20250410_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='maitrise',
            field=models.BooleanField(default=True, help_text="Cochez cette case si la maîtrise doit s'inscrire à votre activité", verbose_name='Activité avec maîtrise'),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.typededuction', verbose_name='Label'),
        ),
    ]
