# Generated by Django 3.2.23 on 2025-05-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0195_auto_20250527_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='maitrise',
            field=models.BooleanField(default=True, help_text="Cochez cette case si l'équipe encadrante doit s'inscrire à votre activité", verbose_name='Activité avec équipe encadrante'),
        ),
    ]
