# Generated by Django 3.2.23 on 2025-09-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0197_alter_typepiece_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='attestation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='attestations_images/'),
        ),
    ]
