# Generated by Django 3.2.23 on 2025-09-10 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0198_attestation_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attestation',
            name='image',
        ),
    ]
