# Generated by Django 3.2.23 on 2025-09-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0199_remove_attestation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Signature'),
        ),
    ]
