# Generated by Django 3.2.23 on 2025-09-10 15:14

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0200_utilisateur_signature_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='signature_image',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to=core.models.chemin_signature),
        ),
    ]
