# Generated by Django 3.2.23 on 2025-09-10 15:38

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0201_auto_20250910_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='signature_image',
            field=models.FileField(blank=True, null=True, upload_to=core.models.chemin_signature),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='signature',
            field=models.ForeignKey(blank=True, help_text="Sélectionnez une signature d'emails favorite dans la liste. Il est possible de créer de nouvelles signatures depuis le menu Paramétrage > Signatures d'emails.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='utilisateur_signature', to='core.signatureemail', verbose_name="Signature d'emails"),
        ),
    ]
