# Generated by Django 3.2.23 on 2025-09-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0202_auto_20250910_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='interne',
            field=models.BooleanField(default=False, help_text="Cochez cette case si vous souhaitez avoir le questionnaire habituel de Sacadoc destiné aux camps d'été", verbose_name='Mutualisation questionnaire'),
        ),
    ]
