# Generated by Django 3.2.23 on 2025-10-09 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0204_auto_20251008_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comptabudget',
            name='analytiques',
        ),
    ]
